### ISSUE TITLE
Build-deploy process and documentation needed

### ISSUE THREAD

**Issue by lee-40square** [zurb/foundation-apps-template#26]
There is no documentation on the build-deploy process beyond a dev environment. Furthermore, there actually doesn't seem to be anything in the Gulp script to run a prod server which I would expect in the build task.

I think what we need is some documentation for a production build and deployment. Some points that should be included in the documentation:

* Adding a basic server script to the Gulp tasks for production
* Running the build with the --production flag
* Pushing only the required files to a production server
* Tips on deploying to Heroku

**Comment by gakimball** [comment]
Hey Lee, sorry for the _supremely_ late response. :)

We tend to shy away from writing about production environments for the Foundation frameworks, because in general they're designed to be as environment-agnostic as possible, and this applies to Foundation for Apps. We rely on our community to contribute integrations, because there's too many possibilities out there for us to account for.

Now, F4A is a complex beast at the moment, so maybe at first glance it looks like it would have some special requirements, but it's just another Angular library, so it can be served any way an Angular application would be.

To be sure, though, we probably haven't done a good job explaining the concept of "don't worry, it's just an Angular site." We do probably have developers who are new to Angular trying to use F4A, but at that point it's not really our place to explain to developers how Angular works. There are many resources out there to learn how to develop and deploy Angular apps, and we're just one piece of that process.

A good start would be to just document our template, which we don't currently do. Foundation for Sites 6 has [thorough documentation](http://foundation.zurb.com/sites/docs/starter-projects.html) on the two templates we distribute for it, explaining the build processes, the `--production` flag, and so on. We can add a page to the Apps docs explaining all these same pieces, and also get into how the `dist/` folder works and deploying a static app to a server.

We've got big plans for Apps next year, so stay tuned :) And thanks for using the framework!

**Comment by lee-40square** [comment]
No worries at all. Over the past few months I've grown a lot through the process. To the point where it seems just as easy to use Sites 6 and strap Angular onto that. :-)

Keep doing what you guys are doing it's great! Looking forward to seeing what you're planning for the next iteration of F4A.
